WORDS = [
    {"word": "achieve", "choices": ["達成する", "失う", "拒否する", "避ける"], "answer": "達成する"},
    {"word": "accept", "choices": ["拒否する", "受け入れる", "疑う", "壊す"], "answer": "受け入れる"},
    {"word": "available", "choices": ["利用可能な", "高価な", "危険な", "不足した"], "answer": "利用可能な"},
    {"word": "benefit", "choices": ["損害", "利益", "費用", "危険"], "answer": "利益"},
    {"word": "confirm", "choices": ["否定する", "確認する", "変更する", "延期する"], "answer": "確認する"},
    {"word": "consider", "choices": ["無視する", "考慮する", "拒否する", "破壊する"], "answer": "考慮する"},
    {"word": "decide", "choices": ["迷う", "決定する", "拒否する", "延期する"], "answer": "決定する"},
    {"word": "deliver", "choices": ["配達する", "受け取る", "壊す", "拒否する"], "answer": "配達する"},
    {"word": "demand", "choices": ["供給", "要求", "拒否", "提案"], "answer": "要求"},
    {"word": "develop", "choices": ["破壊する", "開発する", "停止する", "拒否する"], "answer": "開発する"},
    {"word": "effective", "choices": ["効果的な", "高価な", "危険な", "無意味な"], "answer": "効果的な"},
    {"word": "efficient", "choices": ["非効率な", "効率的な", "危険な", "不足した"], "answer": "効率的な"},
    {"word": "increase", "choices": ["減少する", "増加する", "維持する", "拒否する"], "answer": "増加する"},
    {"word": "improve", "choices": ["悪化させる", "改善する", "停止する", "隠す"], "answer": "改善する"},
    {"word": "include", "choices": ["除外する", "含む", "拒否する", "壊す"], "answer": "含む"},
    {"word": "inform", "choices": ["隠す", "知らせる", "拒否する", "疑う"], "answer": "知らせる"},
    {"word": "manage", "choices": ["管理する", "破壊する", "拒否する", "無視する"], "answer": "管理する"},
    {"word": "maintain", "choices": ["維持する", "壊す", "拒否する", "変更する"], "answer": "維持する"},
    {"word": "provide", "choices": ["要求する", "提供する", "隠す", "拒否する"], "answer": "提供する"},
    {"word": "require", "choices": ["必要とする", "提供する", "節約する", "避ける"], "answer": "必要とする"},

    {"word": "opportunity", "choices": ["危険", "機会", "問題", "制限"], "answer": "機会"},
    {"word": "possibility", "choices": ["不可能", "可能性", "義務", "結果"], "answer": "可能性"},
    {"word": "responsibility", "choices": ["責任", "自由", "利益", "危険"], "answer": "責任"},
    {"word": "situation", "choices": ["状況", "位置", "結果", "理由"], "answer": "状況"},
    {"word": "solution", "choices": ["問題", "原因", "解決策", "結果"], "answer": "解決策"},
    {"word": "schedule", "choices": ["計画表", "結果", "問題", "制限"], "answer": "計画表"},
    {"word": "policy", "choices": ["規則", "方針", "危険", "提案"], "answer": "方針"},
    {"word": "result", "choices": ["原因", "結果", "過程", "問題"], "answer": "結果"},
    {"word": "reason", "choices": ["結果", "理由", "提案", "危険"], "answer": "理由"},
    {"word": "effect", "choices": ["原因", "効果", "問題", "過程"], "answer": "効果"},

    {"word": "customer", "choices": ["店員", "顧客", "上司", "同僚"], "answer": "顧客"},
    {"word": "employee", "choices": ["雇用主", "従業員", "顧客", "管理者"], "answer": "従業員"},
    {"word": "manager", "choices": ["部下", "管理者", "顧客", "同僚"], "answer": "管理者"},
    {"word": "department", "choices": ["会社", "部門", "市場", "工場"], "answer": "部門"},
    {"word": "company", "choices": ["市場", "会社", "工場", "顧客"], "answer": "会社"},

    {"word": "order", "choices": ["注文", "拒否", "結果", "問題"], "answer": "注文"},
    {"word": "payment", "choices": ["支払い", "利益", "契約", "注文"], "answer": "支払い"},
    {"word": "price", "choices": ["価値", "価格", "利益", "費用"], "answer": "価格"},
    {"word": "cost", "choices": ["利益", "費用", "結果", "支払い"], "answer": "費用"},
    {"word": "profit", "choices": ["損失", "利益", "費用", "価格"], "answer": "利益"},

    {"word": "agreement", "choices": ["契約", "拒否", "問題", "結果"], "answer": "契約"},
    {"word": "contract", "choices": ["計画", "契約", "結果", "方針"], "answer": "契約"},
    {"word": "condition", "choices": ["条件", "状況", "結果", "理由"], "answer": "条件"},
    {"word": "deadline", "choices": ["開始日", "締切", "結果", "予定"], "answer": "締切"},
    {"word": "delay", "choices": ["前進", "遅れ", "結果", "成功"], "answer": "遅れ"},
]
